#ifndef BASEDEFINITIONS_H
#define BASEDEFINITIONS_H

#define MAX_TILES_X (650/50)
#define MAX_TILES_Y (500/50)

#define MAX_ENEMY_AMOUNT 6

#define TILE_SIZE 50
#define PLATFORM_SIZE_Y	20

#define ENEMY_RUN_ACCEL 1.3
#define ENEMY_FRAME_AMOUNT 2

#define CHARACTER_START_POSITION_X 20
#define CHARACTER_START_POSITION_Y PLATFORM_SIZE_Y

#define CHARACTER_RUN_ACCEL 1.2
#define CHARACTER_FRAME_AMOUNT 2

#define CHARACTER_SIZE_X 50
#define CHARACTER_SIZE_Y 50

#define BACKGROUND_POSITION_Z 1
#define EXIT_POSITION_Z 2
#define PLATFORM_POSITION_Z 2
#define CHARACTER_POSITION_Z 4
#define ENEMY_POSITION_Z 3

// TODO fetch from KOS
#define SCREEN_SIZE_X	640
#define SCREEN_SIZE_Y	480

#define MIDDLE_OF_SCREEN_X	320
#define MIDDLE_OF_SCREEN_Y	240

#define GRAVITY 1

#endif
