include Makefile.common

all: complete

complete: make_folder build_develop

make_folder:
	-mkdir web

clean:
	-rmdir /s /q web

TARI_PATH = ..\addons\libtari
ADDITIONAL_PRELOADS = --preload-file assets --preload-file assets\sprites@sprites
include ../addons/libtari/Makefile.commonweb